apiVersion: skaffold/v2beta2
kind: Config

metadata:
  name: sample

build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: docker.pkg.github.com/roygi/infrastructure/sample

test:
  - image: docker.pkg.github.com/roygi/infrastructure/sample
    structureTests:
      - './docker_test.yaml'

deploy:
  helm:
    releases:
      - name: sample
        namespace: demo
        chartPath: helm/sample
        packaged:
          appVersion: "{{.VERSION}}"
          version: "{{.VERSION}}"

profiles:
  - name: dev
    activation:
      - kubeContext: minikube
    portForward:
      - resourceType: deployment
        resourceName: sample
        namespace: demo
        port: 8080
        localPort: 9000

  - name: sta
    build:
      local:
        push: true
    activation:
      - kubeContext: digital

  - name: prod
    build:
      local:
        push: true
    activation:
      - kubeContext: digital
