apiVersion: skaffold/v2beta2
kind: Config

metadata:
  name: sample

build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: docker.pkg.github.com/roygi/infrastructure/sample

test:
  - image: docker.pkg.github.com/roygi/infrastructure/sample
    structureTests:
      - './docker_test.yaml'

deploy:
  helm:
    releases:
      - name: sample
        values:
          image.repository: docker.pkg.github.com/roygi/infrastructure/sample
        namespace: demo
        chartPath: helm/sample

profiles:
  - name: dev
    activation:
      - kubeContext: minikube
    portForward:
      - resourceType: deployment
        resourceName: sample
        namespace: demo
        port: 8080
        localPort: 9000

  - name: stag
    activation:
      - kubeContext: dev_cluster
    build:
      local:
        push: true
        useDockerCLI: true
    deploy:
      helm:
        releases:
          - name: sample
            namespace: roygi
            chartPath: helm/sample
            packaged:
              appVersion: "{{.VERSION}}"
              version: "{{.VERSION}}"

  - name: prod
    activation:
      - kubeContext: prod_cluster
    build:
      local:
        push: true
        useDockerCLI: true
    deploy:
      helm:
        releases:
          - name: sample
            namespace: roygi
            chartPath: helm/sample
            packaged:
              appVersion: "{{.VERSION}}"
              version: "{{.VERSION}}"
            setValues:
              service.type: ClusterIP
              replicaCount: 1
              ingress.enabled: false


