name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build
      run: make

    # Runs the test
    - name: Test
      run: make test
